### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by SjVer** [williamd1k0/gdscript-playground#14]
Hey. I'm working on a somewhat similar project, but i wondered how you got the markdown to work? I'm using a different language, but i'd love to hear the how you approached the syntax highlighting and stuff.

Thanks in advance!

**Comment by williamd1k0** [comment]
(Sorry for the delay, it seems that GitHub is not sending notifications to me)

I'm using CodeMirror for the script and output panels.

The syntax highlighting is being defined here:
https://github.com/williamd1k0/gdscript-playground/tree/master/gdscript/static/codemirror/mode/gdscript
