### ISSUE TITLE
Android formatting deletes indented lines 

### ISSUE THREAD

**Issue by polyrain** [williamd1k0/gdscript-playground#23]
On Android 13, when using Chrome, trying to type code under a function (or any indentation) causes the whole line to be erased once you hit enter or begin to open a bracket (`(`). 

I suspect there's some auto formatter at work here that's a little too eager, but it makes it difficult to use the tool on mobile as a result.

**Comment by williamd1k0** [comment]
I can confirm.
I will try to look into it as soon as possible, thanks for reporting.

**Comment by williamd1k0** [comment]
Possibly related: https://github.com/codemirror/codemirror5/issues/6036
